query decks {
  decks {
    created
    faction {
      ability
      created
      dlc {
        created
        id
        image
        key 
        name
      }
      id
      image
      key 
      name
      stats {
        agile
        avenger
        berserker
        bond
        close
        decoy
        heroes
        horn
        mardroeme
        medic
        morale
        muster
        ranged
        scorch
        siege
        specials
        spy
        strengthAverage
        strengthTotal
        strengths
        units
        weather
      }
    }
    id
    leader {
      ability
      created
      dlc {
        created
        id
        image
        key 
        name
      }
      faction {
        ability
        created
        dlc {
          created
          id
          image
          key 
          name
        }
        id
        image
        key 
        name
        stats {
          agile
          avenger
          berserker
          bond
          close
          decoy
          heroes
          horn
          mardroeme
          medic
          morale
          muster
          ranged
          scorch
          siege
          specials
          spy
          strengthAverage
          strengthTotal
          strengths
          units
          weather
        }
      }
      id
      image
      name
      quote
    }
    name
    stats {
      agile
      avenger
      berserker
      bond
      close
      decoy
      heroes
      horn
      mardroeme
      medic
      morale
      muster
      ranged
      scorch
      siege
      specials
      spy
      strengthAverage
      strengthTotal
      strengths
      units
      weather
    }
    units {
      artStyle
      unit {
        combats 
        created
        deckable
        dlc {
          created
          id
          image
          key 
          name
        }
        effectPrefix
        effects {
          ability
          created
          id
          image
          key 
          name
        }
        faction {
          ability
          created
          dlc {
            created
            id
            image
            key 
            name
          }
          id
          image
          key 
          name
          stats {
            agile
            avenger
            berserker
            bond
            close
            decoy
            heroes
            horn
            mardroeme
            medic
            morale
            muster
            ranged
            scorch
            siege
            specials
            spy
            strengthAverage
            strengthTotal
            strengths
            units
            weather
          }
        }
        hero
        id
        images
        modifier
        name
        quote
        scorchMin
        scorchScope 
        special
        strength
      }
    }
    user {
      created
      id
      name
    }
  }
}