query factions($keys: [FactionKey!]) {
  factions(keys: $keys) {
    ability
    created
    dlc {
      created
      id
      image
      key 
      name
    }
    id
    image
    key 
    name
    stats {
      agile
      avenger
      berserker
      bond
      close
      decoy
      heroes
      horn
      mardroeme
      medic
      morale
      muster
      ranged
      scorch
      siege
      specials
      spy
      strengthAverage
      strengthTotal
      strengths
      units
      weather
    }
  }
}