services:
  database:
    image: mongo:8.2.6

  api:
    image: gwent-api
    build:
      context: ../
      dockerfile: msvs/api/Dockerfile
    depends_on:
      - database
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - MONGO_URL=mongodb://database:27017
      - CORS_ORIGIN=https://${HOST_NAME}

  ui:
    image: gwent-ui
    build:
      context: ../
      dockerfile: msvs/ui/Dockerfile
    depends_on:
      - api
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - API_BASE_URL=https://${HOST_NAME}

  router:
    build: ./nginx
    depends_on:
      - api
      - ui
    ports:
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
