services:
  database:
    image: mongo:8.3.7
    restart: ${RESTART_POLICY}
    networks:
      - gwent-oss
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_pass
    secrets:
      - mongo_user
      - mongo_pass
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: '${LOG_MAX_SIZE}'
        max-file: '${LOG_MAX_FILE}'

  api:
    image: gwent-oss-api:${GWENT_OSS_TAG}
    restart: ${RESTART_POLICY}
    networks:
      - gwent-oss
    build:
      context: ../
      dockerfile: msvs/api/Dockerfile
    depends_on:
      - database
    environment:
      MONGO_USERNAME_FILE: /run/secrets/mongo_user
      MONGO_PASSWORD_FILE: /run/secrets/mongo_pass
      LOG_LEVEL: ${LOG_LEVEL}
      MONGO_URL: mongodb://database:27017
      CORS_ORIGIN: https://${HOST_NAME}
    secrets:
      - mongo_user
      - mongo_pass
    logging:
      driver: 'json-file'
      options:
        max-size: '${LOG_MAX_SIZE}'
        max-file: '${LOG_MAX_FILE}'

  ui:
    image: gwent-oss-ui:${GWENT_OSS_TAG}
    restart: ${RESTART_POLICY}
    networks:
      - gwent-oss
    build:
      context: ../
      dockerfile: msvs/ui/Dockerfile
    depends_on:
      - api
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - API_BASE_URL=https://${HOST_NAME}
    logging:
      driver: 'json-file'
      options:
        max-size: '${LOG_MAX_SIZE}'
        max-file: '${LOG_MAX_FILE}'

  router:
    build:
      context: caddy
      dockerfile: caddy.Dockerfile
    restart: ${RESTART_POLICY}
    networks:
      - gwent-oss
    depends_on:
      - api
      - ui
    environment:
      - HOST_NAME=${HOST_NAME}
      - LOCAL_CERTS=${LOCAL_CERTS}
      - DEBUG=${DEBUG}
      - LIMIT_HTTP_EVENTS_NOT_AUTH=${LIMIT_HTTP_EVENTS_NOT_AUTH}
      - LIMIT_HTTP_EVENTS_YES_AUTH=${LIMIT_HTTP_EVENTS_YES_AUTH}
      - LIMIT_HTTP_WINDOW_NOT_AUTH=${LIMIT_HTTP_WINDOW_NOT_AUTH}
      - LIMIT_HTTP_WINDOW_YES_AUTH=${LIMIT_HTTP_WINDOW_YES_AUTH}
      - LIMIT_HTTP_BURST_NOT_AUTH=${LIMIT_HTTP_BURST_NOT_AUTH}
      - LIMIT_HTTP_BURST_YES_AUTH=${LIMIT_HTTP_BURST_YES_AUTH}
      - LIMIT_WS_EVENTS_NOT_AUTH=${LIMIT_WS_EVENTS_NOT_AUTH}
      - LIMIT_WS_EVENTS_YES_AUTH=${LIMIT_WS_EVENTS_YES_AUTH}
      - LIMIT_WS_WINDOW_NOT_AUTH=${LIMIT_WS_WINDOW_NOT_AUTH}
      - LIMIT_WS_WINDOW_YES_AUTH=${LIMIT_WS_WINDOW_YES_AUTH}
      - LIMIT_WS_BURST_NOT_AUTH=${LIMIT_WS_BURST_NOT_AUTH}
      - LIMIT_WS_BURST_YES_AUTH=${LIMIT_WS_BURST_YES_AUTH}
    ports:
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    logging:
      driver: 'json-file'
      options:
        max-size: '${LOG_MAX_SIZE}'
        max-file: '${LOG_MAX_FILE}'

volumes:
  mongo_data:
  caddy_data:
  caddy_config:

secrets:
  mongo_user:
    file: ./secrets/mongo_user
  mongo_pass:
    file: ./secrets/mongo_pass

networks:
  gwent-oss:
    name: ${NETWORK_NAME}
    driver: bridge
