# Scalar definitions defined in ./scalars.ts
scalar DateTime
scalar SemVer

enum Combat {
  "Close"
  CLOSE
  "Ranged"
  RANGED
  "Siege"
  SIEGE
}

enum DlcKey {
  "Blood and Wine"
  BLOOD_AND_WINE
  "Gwent: The Witcher Card Game"
  GWENT_THE_WITCHER_CARD_GAME
  "Hearts of Stone"
  HEARTS_OF_STONE
}

enum EffectKey {
  "Agile"
  AGILE
  "Summon Avenger"
  AVENGER
  "Berserker"
  BERSERKER
  "Tight Bond"
  BOND
  "Decoy"
  DECOY
  "Commander's Horn"
  HORN
  "Mardroeme"
  MARDROEME
  "Medic"
  MEDIC
  "Morale Boost"
  MORALE
  "Muster"
  MUSTER
  "Scorch"
  SCORCH
  "Spy"
  SPY
  "Weather"
  WEATHER
}

enum FactionKey {
  "Monsters"
  MONSTERS
  "Neutral"
  NEUTRAL
  "Nilfgaardian Empire"
  NILFGAARDIAN_EMPIRE
  "Northern Realms"
  NORTHERN_REALMS
  "Scoia'tael"
  SCOIA_TAEL
  "Skellige"
  SKELLIGE
}

enum GameStatus {
  "Players are choosing their decks to use for the game."
  DECKING
  "The order of player turns is being decided. Happens automatically unless there is a single player with a Scoia'tael faction deck who can then choose which player starts."
  ORDERING
  "Players are potentially redrawing the cards in their hand."
  REDRAWING
  "Players are playing rounds of the game."
  PLAYING
  "Play has ended."
  DONE
}

enum GameDeckStatus {
  "Player is choosing their deck to use for the game."
  CHOOSING
  "Player is optionally selecting units to redraw from their selected deck."
  REDRAWING
  "Player game deck is finalized and ready to play."
  SET
}

enum MoveReasonType {
  "Deployment by a game player to the battlefield."
  DEPLOY
  "Mustered when matching Muster unit added to battlefield."
  MUSTER
  "Revived by Medic added to battlefield."
  REVIVE
  "Summoned when matching Avenger unit removed from battlefield."
  SUMMON
  "Transformed when Mardroeme unit added to battlefield row."
  TRANSFORM
}

enum GameUnitOrigin {
  "Unit came from the users Hand."
  HAND
  "Unit came from the users Lost pile."
  Discard
  "Unit came from an opponent placing it on their battlefield."
  OPPONENT
  "Unit came from the users Draw pile."
  UNDRAWN
  "Unit came from a non-deckable source."
  NONDECK
}

enum RoundResult {
  "Beat all other players in the round."
  WON
  "Beaten by another player in the round."
  LOST
  "Tied for the win with another player in the round."
  DREW
}

enum SettingKey {
  SESSION_TIMEOUT_SECONDS
}

enum SettingType {
  NUMBER
}

type Application {
  "The current build number of the application running."
  build: Int!
  "The current version of the application running."
  version: SemVer!
}

type Deck @entity {
  created: DateTime! @column
  faction: Faction! @column(overrideType: "ObjectId")
  id: ID! @id @map(path: "_id")
  leader: Leader! @column(overrideType: "ObjectId")
  name: String! @column
  stats: UnitStats! @column
  units: [DeckUnit!]! @column(overrideType: "Array<DeckUnitDbObject>")
  user: User! @column(overrideType: "ObjectId")
}

"A Unit in a user created Deck."
type DeckUnit @entity {
  artStyle: Int! @column
  unit: Unit! @column(overrideType: "ObjectId")
}

type Dlc @entity {
  created: DateTime! @column
  id: ID! @id @map(path: "_id")
  image: String! @column
  key: DlcKey! @column
  name: String! @column
}

type Effect @entity {
  ability: String! @column
  created: DateTime! @column
  id: ID! @id @map(path: "_id")
  image: String! @column
  key: EffectKey! @column
  name: String! @column
}

type Faction @entity {
  ability: String @column
  created: DateTime! @column
  dlc: Dlc @column(overrideType: "ObjectId")
  id: ID! @id @map(path: "_id")
  image: String! @column
  key: FactionKey! @column
  name: String! @column
  stats: UnitStats! @column
}

type Game @entity {
  config: GameConfig! @column
  created: DateTime! @column
  creator: User! @column(overrideType: "ObjectId")
  id: ID! @id @map(path: "_id")
  players: [GamePlayer!]! @column(overrideType: "Array<GamePlayerDbObject>")
  "The current round the game is in. 1-based indexing. A value of zero indicates the game has not yet started."
  round: Int! @column
  status: GameStatus! @column
  "Whose turn it currently is to make a move."
  turn: GamePlayer @column(overrideType: "ObjectId")
  updated: DateTime! @column
  victors: [User!]! @column(overrideType: "Array<ObjectId>")
}

type GameConfig {
  "The number of lives each player starts with at the beginning of the game."
  lives: Int! @column
}

type GameDeck @entity {
  "The units which have been sent to the graveyard"
  discard: [DeckUnit!]! @column(overrideType: "Array<DeckUnitDbObject>")
  "A snapshot of the user deck when it was selected for the game"
  from: Deck @column(overrideType: "DeckDbObject")
  "The currently playable units"
  hand: [DeckUnit!]! @column(overrideType: "Array<DeckUnitDbObject>")
  "Units which the player has chosen to redraw to be replaced by a different random undrawn unit."
  redraws: [Redraw!]! @column(overrideType: "Array<RedrawDbObject>")
  "The units which have not yet been drawn"
  undrawn: [DeckUnit!]! @column(overrideType: "Array<DeckUnitDbObject>")
}

type GamePlayer @entity(additionalFields: [{ path: "deck", type: "GameDeckDbObject" }]) {
  "The number of cards in the game deck of the player. Only visible once all players are ready."
  counts: GamePlayerUnitCounts
  "The faction the player chose for the game. Only visible once all players are ready."
  faction: Faction
  "The leader the player chose for the game. Only visible once all players are ready."
  leader: Leader
  "The precedence of order the player takes their turn relative to other players. Zero based indexing."
  order: Int @column
  "Whether or not a user has their game deck set to play the game."
  ready: Boolean! @column
  "Whether or not the player is currently choosing a Discarded Unit to revive with a Medic."
  reviving: Boolean! @column
  rounds: [PlayerRound!]! @column(overrideType: "Array<PlayerRoundDbObject>")
  user: User! @column(overrideType: "ObjectId")
}

type GamePlayerUnitCounts {
  discard: Int!
  hand: Int!
  undrawn: Int!
}

"A unit on the field of battle."
type FieldUnit @entity {
  artStyle: Int! @column
  effectiveStrength: Int @column
  effects: [FieldUnitEffect!] @column(overrideType: "Array<FieldUnitEffectDbObject>")
  row: Combat! @column
  unit: Unit! @column(overrideType: "ObjectId")
}

"A Unit weathering the battlefield."
type WeatherUnit @entity {
  artStyle: Int! @column
  unit: Unit! @column(overrideType: "ObjectId")
}

"A Unit participating in a Game."
union GameUnit @union(discriminatorField: "type") = DeckUnit | FieldUnit | WeatherUnit

type FieldUnitEffect @entity {
  operator: String! @column
  reason: EffectReason! @column(overrideType: "EffectReasonDbObject")
  total: Int! @column
}

type EffectFromUnit @entity(additionalFields: [{ path: "type", type: "EffectReasonType" }]) {
  effect: Effect! @column(overrideType: "ObjectId")
  unit: Unit! @column(overrideType: "ObjectId")
}

type EffectFromLeader @entity(additionalFields: [{ path: "type", type: "EffectReasonType" }]) {
  leader: Leader! @column(overrideType: "ObjectId")
}

union EffectReason @union(discriminatorField: "type") = EffectFromUnit | EffectFromLeader

type Leader @entity {
  ability: String! @column
  created: DateTime! @column
  dlc: Dlc @column(overrideType: "ObjectId")
  faction: Faction! @column(overrideType: "ObjectId")
  id: ID! @id @map(path: "_id")
  image: String! @column
  name: String! @column
  quote: String! @column
}

"A unit which was impacted by another unit."
type Impact @entity {
  unit: GameUnit @column(overrideType: "GameUnitDbObject")
  user: User! @column(overrideType: "ObjectId")
  source: GameUnitSource @column(overrideType: "GameUnitSourceDbObject")
}

type MoveLeader @entity(additionalFields: [{ path: "type", type: "MoveType" }]) {
  created: DateTime! @column
  leader: Leader! @column(overrideType: "ObjectId")
}

type MovePass @entity(additionalFields: [{ path: "type", type: "MoveType" }]) {
  created: DateTime! @column
}

type MoveUnit @entity(additionalFields: [{ path: "type", type: "MoveType" }]) {
  "When the Move was made."
  created: DateTime! @column
  "The Unit which was Moved."
  unit: GameUnit! @column(overrideType: "GameUnitDbObject")
  "Other Units the Move impacted in the Game."
  impacts: [Impact!] @column(overrideType: "Array<ImpactDbObject>")
  "What caused the Move to happen."
  reason: MoveUnitReason! @column(overrideType: "MoveUnitReasonDbObject")
  "Where the Unit which made the Move came from."
  source: GameUnitSource! @column(overrideType: "GameUnitSourceDbObject")
  "The Game Player that was Spied on."
  target: User @column(overrideType: "ObjectId")
}

type MoveUnitReason @entity {
  type: MoveReasonType! @column
  unit: GameUnit @column(overrideType: "GameUnitDbObject")
}

type GameUnitSource @entity {
  origin: GameUnitOrigin! @column
  user: User @column(overrideType: "ObjectId")
}

union Move @union(discriminatorField: "type") = MoveLeader | MovePass | MoveUnit

type PlayerRound @entity {
  close: PlayerCombatRow! @column(overrideType: "PlayerCombatRowDbObject")
  moves: [Move!]! @column(overrideType: "Array<MoveDbObject>")
  passed: Boolean! @column
  ranged: PlayerCombatRow! @column(overrideType: "PlayerCombatRowDbObject")
  result: RoundResult @column
  score: Int! @column
  siege: PlayerCombatRow! @column(overrideType: "PlayerCombatRowDbObject")
  weathers: [WeatherUnit!]! @column(overrideType: "Array<WeatherUnitDbObject>")
}

type PlayerCombatRow @entity {
  score: Int! @column
  units: [FieldUnit!]! @column(overrideType: "Array<FieldUnitDbObject>")
  modifier: FieldUnit @column(overrideType: "FieldUnitDbObject")
}

type Redraw @entity {
  from: DeckUnit! @column(overrideType: "DeckUnitDbObject")
  to: DeckUnit! @column(overrideType: "DeckUnitDbObject")
}

type Setting {
  key: SettingKey!
  label: String!
  type: SettingType!
  value: String!
}

type Unit @entity {
  combats: [Combat!] @column
  created: DateTime! @column
  deckable: Boolean! @column
  dlc: Dlc @column(overrideType: "ObjectId")
  effectPrefix: String @column
  effects: [Effect!] @column(overrideType: "ObjectId[]")
  faction: Faction! @column(overrideType: "ObjectId")
  hero: Boolean @column
  id: ID! @id @map(path: "_id")
  images: [String!]! @column
  modifier: Boolean! @column
  name: String! @column
  quote: String! @column
  scorchMin: Int @column
  scorchScope: Combat @column
  special: Boolean @column
  strength: Int @column
}

type UnitStats {
  agile: Int!
  avenger: Int!
  berserker: Int!
  bond: Int!
  close: Int!
  decoy: Int!
  heroes: Int!
  horn: Int!
  mardroeme: Int!
  medic: Int!
  morale: Int!
  muster: Int!
  ranged: Int!
  strengths: Int!
  scorch: Int!
  siege: Int!
  specials: Int!
  spy: Int!
  strengthAverage: Float!
  strengthTotal: Int!
  units: Int!
  weather: Int!
}

type User @entity(additionalFields: [{ path: "password", type: "string" }]) {
  created: DateTime! @column(overrideType: "Date")
  id: ID! @id
  name: String! @column
}

type GameDeckSet {
  deck: GameDeck!
  game: Game!
}

type GameUnitRedrawn {
  from: DeckUnit!
  deck: GameDeck!
  game: Game!
  to: DeckUnit!
}

type RoundEndedForDeck {
  deck: GameDeck!
  game: Game!
}

type UnitPlayedFromDeck {
  deck: GameDeck!
  game: Game!
  handed: [DeckUnit!]
  unit: DeckUnit!
}

type UnitPlayedOnGame {
  game: Game!
  unit: DeckUnit!
}

input DeckUnitInput {
  "For units with multiple art styles, the art style to use (1-based indexing)."
  artStyle: Int = 1
  id: ID!
}

type Query {
  "Information about the application running."
  application: Application!

  "All decks created by the authenticated user."
  decks: [Deck!]!

  "The current user on the session if they are authenticated."
  currentUser: User

  "All factions which a leader, unit or deck can belong to."
  factions(keys: [FactionKey!]): [Faction!]!

  "A game by its ID."
  game(id: ID!): Game!

  "The deck selected to be played for the given game."
  gameDeck(game: ID!): GameDeck

  "All games which a user created or is part of."
  games: [Game!]!

  "All leaders available to build decks with."
  leaders(factions: [FactionKey!]): [Leader!]!

  "The settings configured for the application."
  settings: [Setting!]!

  "All units available to build decks with."
  units(factions: [FactionKey!], deckable: Boolean): [Unit!]!
}

type Mutation {
  "Create a user-defined deck."
  addDeck(name: String!, faction: FactionKey!, leader: ID!, units: [DeckUnitInput!]!): Deck!

  "Create a game of Gwent between the authenticated user and another player."
  addGame(opponentNames: [String!]!): Game!

  "Create a user."
  addUser(name: String!, password: String!): User!

  "Authenticate a user."
  login(name: String!, password: String!): User!

  "De-authenticate a user."
  logout: Boolean!

  "Pass for the rest of the round in a game."
  playPass(game: ID!): Game!

  "Play a Unit card in a game. If a unit is eligible for multiple different types of Combat, one must be specified. Specify target for Decoy or Spy."
  playUnit(game: ID!, unit: ID!, combat: Combat, target: ID): Game!

  "Mark player as ready to play the game, no more deck modifications allowed."
  ready(game: ID!): Game!

  "Replace a card in hand with a random one from the deck, before a game starts."
  redraw(game: ID!, unit: ID!): DeckUnit!

  "Choose which deck will be used for the game."
  setDeck(game: ID!, deck: ID!): GameDeck!

  "Set the order in which players will take turns during a game."
  setOrder(game: ID!, users: [ID!]): Game!
}

type Subscription {
  "A deck has been added for a user."
  deckAdded: Deck!
  "A deck has been set for a game the user is a player on."
  deckSet: GameDeckSet!
  "A game has been added that the user is player on."
  gameAdded: Game!
  "A game the user is a player on has been marked as ready by a player."
  gameReady: Game!
  "All decks have been set for a game the user is a player on."
  gameSet: Game!
  "The order has been set for a game the user is a player on."
  orderSet: Game!
  "A user has passed the rest of the round for a game."
  passPlayed: Game!
  "A round has finished which triggers updates to the GameDeck for each player on the game."
  roundEndedForDeck: RoundEndedForDeck!
  "The unit card played from a deck and the updated GameDeck."
  unitPlayedFromDeck: UnitPlayedFromDeck!
  "The unit card played on a game and the updated Game."
  unitPlayedOnGame: UnitPlayedOnGame!
  "A unit was redrawn for a game deck the user owns."
  unitRedrawn: GameUnitRedrawn!
}
