fragment DeckFragment on Deck {
  id
  created
  name
  faction {
    ...FactionFragment
  }
  leader {
    name
    ability
    image
  }
  stats {
    units
    specials
    heroes
    close
    ranged
    siege
    agile
    strengthTotal
    strengthAverage
  }
}
