fragment FieldUnitEffect on FieldUnitEffect {
  operator
  total
  reason {
    ... on EffectFromUnit {
      effect {
        id
        name
      }
      unit {
        id
        name
      }
    }
    ... on EffectFromLeader {
      leader {
        id
        name
      }
    }
  }
}
