fragment MoveUnit on MoveUnit {
  created
  unit {
    ...TacoUnit
  }
  impacts {
    ...Impact
  }
  reason {
    type
    unit {
      ...MoveUnitReasonUnit
    }
  }
  source {
    origin
  }
  target {
    id
    name
  }
}
