fragment MoveUnit on MoveUnit {
  created
  unit {
    ...GameUnitFragment
  }
  impacts {
    ...Impact
  }
  reason {
    type
    unit {
      unit {
        name
      }
    }
  }
  source {
    origin
  }
}
