fragment PlayerRound on PlayerRound {
  close {
    ...PlayerCombatRow
  }
  moves {
    ...Move
  }
  passed
  ranged {
    ...PlayerCombatRow
  }
  result
  score
  siege {
    ...PlayerCombatRow
  }
  weathers {
    ...WeatherUnit
  }
}
