fragment PlayerRound on PlayerRound {
  close {
    ...PlayerCombatRowFragment
  }
  moves {
    ...Move
  }
  passed
  ranged {
    ...PlayerCombatRowFragment
  }
  result
  score
  siege {
    ...PlayerCombatRowFragment
  }
}
