fragment Unit on Unit {
  combats
  deckable
  dlc {
    name
    image
    key
  }
  effectPrefix
  effects {
    ...UnitEffect
  }
  faction {
    image
    key
    name
  }
  hero
  id
  images
  modifier
  name
  quote
  special
  strength
}
