import combineUnitStats from '../../src/combine-unit-stats'

const neutralStats = {
  agile: 1,
  avenger: 1,
  berserker: 0,
  bond: 0,
  close: 11,
  decoy: 3,
  heroes: 5,
  horn: 4,
  mardroeme: 0,
  medic: 1,
  morale: 1,
  muster: 6,
  ranged: 6,
  scorch: 4,
  siege: 1,
  specials: 22,
  spy: 1,
  strengthAverage: 92 / 39,
  strengths: 17,
  strengthTotal: 92,
  units: 39,
  weather: 13,
}

describe('combine-unit-stats', () => {
  it('returns doubled if combining same stats', () => {
    expect(
      combineUnitStats(
        {
          agile: 1,
          avenger: 2,
          berserker: 3,
          bond: 4,
          close: 5,
          decoy: 6,
          heroes: 7,
          horn: 8,
          mardroeme: 9,
          medic: 10,
          morale: 11,
          muster: 12,
          ranged: 13,
          scorch: 14,
          siege: 15,
          specials: 16,
          spy: 17,
          strengthAverage: 19 / 20,
          strengths: 18,
          strengthTotal: 19,
          units: 20,
          weather: 21,
        },
        {
          agile: 1,
          avenger: 2,
          berserker: 3,
          bond: 4,
          close: 5,
          decoy: 6,
          heroes: 7,
          horn: 8,
          mardroeme: 9,
          medic: 10,
          morale: 11,
          muster: 12,
          ranged: 13,
          scorch: 14,
          siege: 15,
          specials: 16,
          spy: 17,
          strengthAverage: 19 / 20,
          strengths: 18,
          strengthTotal: 19,
          units: 20,
          weather: 21,
        }
      )
    ).toEqual({
      agile: 2,
      avenger: 4,
      berserker: 6,
      bond: 8,
      close: 10,
      decoy: 12,
      heroes: 14,
      horn: 16,
      mardroeme: 18,
      medic: 20,
      morale: 22,
      muster: 24,
      ranged: 26,
      scorch: 28,
      siege: 30,
      specials: 32,
      spy: 34,
      strengthAverage: 38 / 40,
      strengths: 36,
      strengthTotal: 38,
      units: 40,
      weather: 42,
    })
  })
  it('returns correct stats if monsters combined with neutrals', () => {
    expect(
      combineUnitStats(
        {
          agile: 3,
          avenger: 0,
          berserker: 0,
          bond: 0,
          close: 30,
          decoy: 0,
          heroes: 4,
          horn: 0,
          mardroeme: 0,
          medic: 0,
          morale: 1,
          muster: 18,
          ranged: 10,
          scorch: 1,
          siege: 4,
          specials: 0,
          spy: 0,
          strengthAverage: 182 / 41,
          strengths: 41,
          strengthTotal: 182,
          units: 41,
          weather: 0,
        },
        neutralStats
      )
    ).toEqual({
      agile: 4,
      avenger: 1,
      berserker: 0,
      bond: 0,
      close: 41,
      decoy: 3,
      heroes: 9,
      horn: 4,
      mardroeme: 0,
      medic: 1,
      morale: 2,
      muster: 24,
      ranged: 16,
      scorch: 5,
      siege: 5,
      specials: 22,
      spy: 1,
      strengthAverage: ((182 / 41) * 41 + (92 / 39) * 39) / (41 + 39),
      strengths: 58,
      strengthTotal: 274,
      units: 80,
      weather: 13,
    })
  })
  it('returns correct stats if nilfgaard combined with neutrals', () => {
    expect(
      combineUnitStats(
        {
          agile: 0,
          avenger: 0,
          berserker: 0,
          bond: 9,
          close: 18,
          decoy: 0,
          heroes: 4,
          horn: 0,
          mardroeme: 0,
          medic: 4,
          morale: 0,
          muster: 0,
          ranged: 13,
          scorch: 0,
          siege: 6,
          specials: 0,
          spy: 3,
          strengthAverage: 181 / 37,
          strengths: 37,
          strengthTotal: 181,
          units: 37,
          weather: 0,
        },
        neutralStats
      )
    ).toEqual({
      agile: 1,
      avenger: 1,
      berserker: 0,
      bond: 9,
      close: 29,
      decoy: 3,
      heroes: 9,
      horn: 4,
      mardroeme: 0,
      medic: 5,
      morale: 1,
      muster: 6,
      ranged: 19,
      scorch: 4,
      siege: 7,
      specials: 22,
      spy: 4,
      strengthAverage: ((181 / 37) * 37 + (92 / 39) * 39) / (37 + 39),
      strengths: 54,
      strengthTotal: 273,
      units: 76,
      weather: 13,
    })
  })
  it('returns correct stats if northern realms combined with neutrals', () => {
    expect(
      combineUnitStats(
        {
          agile: 0,
          avenger: 0,
          berserker: 0,
          bond: 11,
          close: 17,
          decoy: 0,
          heroes: 4,
          horn: 0,
          mardroeme: 0,
          medic: 1,
          morale: 1,
          muster: 0,
          ranged: 8,
          scorch: 0,
          siege: 9,
          specials: 0,
          spy: 3,
          strengthAverage: 163 / 34,
          strengths: 34,
          strengthTotal: 163,
          units: 34,
          weather: 0,
        },
        neutralStats
      )
    ).toEqual({
      agile: 1,
      avenger: 1,
      berserker: 0,
      bond: 11,
      close: 28,
      decoy: 3,
      heroes: 9,
      horn: 4,
      mardroeme: 0,
      medic: 2,
      morale: 2,
      muster: 6,
      ranged: 14,
      scorch: 4,
      siege: 10,
      specials: 22,
      spy: 4,
      strengthAverage: ((163 / 34) * 34 + (92 / 39) * 39) / (34 + 39),
      strengths: 51,
      strengthTotal: 255,
      units: 73,
      weather: 13,
    })
  })
  it('returns correct stats if scoiatael combined with neutrals', () => {
    expect(
      combineUnitStats(
        {
          agile: 9,
          avenger: 0,
          berserker: 0,
          bond: 0,
          close: 22,
          decoy: 0,
          heroes: 4,
          horn: 0,
          mardroeme: 0,
          medic: 3,
          morale: 2,
          muster: 9,
          ranged: 24,
          scorch: 1,
          siege: 1,
          specials: 0,
          spy: 0,
          strengthAverage: 185 / 38,
          strengths: 38,
          strengthTotal: 185,
          units: 38,
          weather: 0,
        },
        neutralStats
      )
    ).toEqual({
      agile: 10,
      avenger: 1,
      berserker: 0,
      bond: 0,
      close: 33,
      decoy: 3,
      heroes: 9,
      horn: 4,
      mardroeme: 0,
      medic: 4,
      morale: 3,
      muster: 15,
      ranged: 30,
      scorch: 5,
      siege: 2,
      specials: 22,
      spy: 1,
      strengthAverage: ((185 / 38) * 38 + (92 / 39) * 39) / (38 + 39),
      strengths: 55,
      strengthTotal: 277,
      units: 77,
      weather: 13,
    })
  })
  it('returns correct stats if skellige combined with neutrals', () => {
    expect(
      combineUnitStats(
        {
          agile: 1,
          avenger: 1,
          berserker: 4,
          bond: 9,
          close: 18,
          decoy: 0,
          heroes: 4,
          horn: 1,
          mardroeme: 4,
          medic: 1,
          morale: 1,
          muster: 4,
          ranged: 13,
          scorch: 1,
          siege: 5,
          specials: 3,
          spy: 0,
          strengthAverage: 174 / 38,
          strengths: 35,
          strengthTotal: 174,
          units: 38,
          weather: 0,
        },
        neutralStats
      )
    ).toEqual({
      agile: 2,
      avenger: 2,
      berserker: 4,
      bond: 9,
      close: 29,
      decoy: 3,
      heroes: 9,
      horn: 5,
      mardroeme: 4,
      medic: 2,
      morale: 2,
      muster: 10,
      ranged: 19,
      scorch: 5,
      siege: 6,
      specials: 25,
      spy: 1,
      strengthAverage: ((174 / 38) * 38 + (92 / 39) * 39) / (38 + 39),
      strengths: 52,
      strengthTotal: 266,
      units: 77,
      weather: 13,
    })
  })
})
