fragment GamePlayerFragment on GamePlayer {
  counts {
    discard
    hand
    undrawn
  }
  faction {
    ...GameFactionFragment
  }
  leader {
    ...GameLeaderFragment
  }
  ready
  rounds {
    close {
      ...PlayerCombatRowFragment
    }
    passed
    ranged {
      ...PlayerCombatRowFragment
    }
    score
    siege {
      ...PlayerCombatRowFragment
    }
  }
  user {
    id
    name
  }
}
