subscription UnitPlayedFromDeck {
  unitPlayedFromDeck {
    game {
      id
    }
    handed {
      ...DeckUnit
    }
    discarded {
      ...DeckUnit
    }
    undiscarded {
      ...DeckUnit
    }
    unit {
      ...DeckUnit
    }
  }
}
