subscription UnitPlayedOnGame {
  unitPlayedOnGame {
    game {
      ...Game
    }
    discarded {
      ...DeckUnit
    }
    undiscarded {
      ...DeckUnitRemoved
    }
    unhanded {
      ...DeckUnitRemoved
    }
  }
}
